# Secrets are generated by Terraform and stored only in Secrets Manager,
# never written to app config files or committed anywhere. ECS reads them
# at container-start time via the task definition's `secrets` block (see
# ecs.tf), so plaintext values never appear in the task definition itself,
# CloudWatch Logs, or the Terraform state's outputs.

resource "random_password" "db_password" {
  length  = 32
  special = false # RDS master password disallows some special characters
}

resource "random_password" "session_secret" {
  length  = 44
  special = false
}

resource "aws_secretsmanager_secret" "db_credentials" {
  name       = "${local.name_prefix}/db-credentials"
  kms_key_id = aws_kms_key.main.arn
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_password.result
  })
}

resource "aws_secretsmanager_secret" "database_url" {
  name       = "${local.name_prefix}/database-url"
  kms_key_id = aws_kms_key.main.arn
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id     = aws_secretsmanager_secret.database_url.id
  secret_string = "postgresql://${var.db_username}:${random_password.db_password.result}@${aws_db_instance.main.endpoint}/${var.db_name}?schema=public&sslmode=require"
}

resource "aws_secretsmanager_secret" "session_secret" {
  name       = "${local.name_prefix}/session-secret"
  kms_key_id = aws_kms_key.main.arn
}

resource "aws_secretsmanager_secret_version" "session_secret" {
  secret_id     = aws_secretsmanager_secret.session_secret.id
  secret_string = random_password.session_secret.result
}
