variable "aws_region" {
  description = "AWS region to deploy into. Must be a region covered by your AWS BAA and only using HIPAA-eligible services (this config only uses HIPAA-eligible services: VPC, ECS Fargate, RDS, S3, KMS, Secrets Manager, CloudTrail, ALB, ECR)."
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name, used in resource naming and tags (e.g. \"pilot\", \"production\")."
  type        = string
  default     = "pilot"
}

variable "project_name" {
  description = "Short name used as a prefix for resource names."
  type        = string
  default     = "carecoord-hub"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.20.0.0/16"
}

variable "availability_zones" {
  description = "Availability zones to spread subnets across. Two is the minimum for an ALB (required regardless of single_nat_gateway)."
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b"]
}

variable "single_nat_gateway" {
  description = "Cost vs. redundancy knob, NOT a compliance one. true (default): one shared NAT gateway for all private subnets, ~half the cost, survives everything except a single-AZ outage taking down outbound internet access temporarily. false: one NAT gateway per AZ, full redundancy, ~2x the cost. Fine to leave true for a pilot; flip before a go-live where an AZ outage causing a brief outage is unacceptable."
  type        = bool
  default     = true
}

variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage_gb" {
  description = "RDS allocated storage in GB."
  type        = number
  default     = 20
}

variable "db_multi_az" {
  description = "Whether RDS should run Multi-AZ for failover. Recommended true for production."
  type        = bool
  default     = false
}

variable "db_name" {
  description = "Postgres database name."
  type        = string
  default     = "care_coord_hub"
}

variable "db_username" {
  description = "Master username for RDS. The password is generated by Terraform and stored in Secrets Manager, never in state as plaintext output."
  type        = string
  default     = "carecoord_admin"
}

variable "db_backup_retention_days" {
  description = "Number of days to retain automated RDS backups."
  type        = number
  default     = 14
}

variable "app_image" {
  description = "Container image (repo:tag) to deploy to ECS. Not kept in sync automatically — every app-code deploy (see DEPLOY.md) registers a new task definition revision directly via the AWS CLI, bypassing Terraform entirely (the ECS service's lifecycle.ignore_changes=[task_definition] is specifically there to let that happen without Terraform fighting it). Update this default when you touch this file for an unrelated reason, so a plan run doesn't propose reverting to a stale image."
  type        = string
  default     = "413790912837.dkr.ecr.us-east-1.amazonaws.com/carecoord-hub-pilot-app:c94af89"
}

variable "app_port" {
  description = "Port the Next.js app listens on inside the container."
  type        = number
  default     = 3000
}

variable "app_cpu" {
  description = "Fargate task CPU units (256 = .25 vCPU)."
  type        = number
  default     = 512
}

variable "app_memory" {
  description = "Fargate task memory in MB."
  type        = number
  default     = 1024
}

variable "app_desired_count" {
  description = "Number of running ECS tasks. 1 (default) is fine for a pilot — deploys have a brief blip instead of staying zero-downtime. Bump to 2+ once that matters."
  type        = number
  default     = 1
}

variable "domain_name" {
  description = "Domain name to serve the app on (e.g. carecoord.yourorg.com). Leave empty to skip Route53/ACM and use the raw ALB DNS name over HTTP only until you're ready to attach a domain — see infra/README.md."
  type        = string
  default     = ""
}

variable "route53_zone_id" {
  description = "Existing Route53 hosted zone ID for domain_name. Required only if domain_name is set and you want Terraform to manage the DNS record and ACM validation."
  type        = string
  default     = ""
}

variable "app_timezone" {
  description = "IANA timezone the app container runs in (e.g. \"America/Denver\") — every compliance-window date calculation (touchpoint cadence, CCP grace period, CNA/graduation due dates) runs in this timezone. Leave empty to run in UTC, which is almost certainly not what you want for a clinic in any US timezone."
  type        = string
  default     = "America/Denver"
}

variable "alert_email" {
  description = "Email address that receives production alerts (app erroring, unreachable, or maxed out). SNS sends a one-time confirmation link to this address on first apply — it must be clicked before alerts actually deliver."
  type        = string
  default     = "mkiefer@riopecosmed.com"
}

variable "alert_phone" {
  description = "Phone number (E.164 format, e.g. \"+15756529588\") that receives production alerts via SMS. Leave empty to skip SMS alerting."
  type        = string
  default     = "+15756529588"
}

variable "waf_rate_limit_per_5min" {
  description = "Requests from a single IP in a 5-minute window before the WAF blocks it. Deliberately generous — a small clinic's staff mostly share one office IP, and a too-low limit would lock out the whole office over normal use, not just an attacker. Tighten this once real traffic patterns are known."
  type        = number
  default     = 3000
}
