variable "aws_region" {
  description = "AWS region to deploy into. Must be a region covered by your AWS BAA and only using HIPAA-eligible services (this config only uses HIPAA-eligible services: VPC, ECS Fargate, RDS, S3, KMS, Secrets Manager, CloudTrail, ALB, ECR)."
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name, used in resource naming and tags (e.g. \"staging\", \"production\")."
  type        = string
  default     = "production"
}

variable "project_name" {
  description = "Short name used as a prefix for resource names."
  type        = string
  default     = "carecoord-hub"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.20.0.0/16"
}

variable "availability_zones" {
  description = "Availability zones to spread subnets across. Two is the minimum for RDS Multi-AZ and an ALB."
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b"]
}

variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage_gb" {
  description = "RDS allocated storage in GB."
  type        = number
  default     = 20
}

variable "db_multi_az" {
  description = "Whether RDS should run Multi-AZ for failover. Recommended true for production."
  type        = bool
  default     = false
}

variable "db_name" {
  description = "Postgres database name."
  type        = string
  default     = "care_coord_hub"
}

variable "db_username" {
  description = "Master username for RDS. The password is generated by Terraform and stored in Secrets Manager, never in state as plaintext output."
  type        = string
  default     = "carecoord_admin"
}

variable "db_backup_retention_days" {
  description = "Number of days to retain automated RDS backups."
  type        = number
  default     = 14
}

variable "app_image" {
  description = "Container image (repo:tag) to deploy to ECS. Leave as the placeholder until you've pushed a real image to the ECR repo this config creates — the ECS service won't start on the placeholder, which is expected on first apply."
  type        = string
  default     = "public.ecr.aws/docker/library/nginx:latest"
}

variable "app_port" {
  description = "Port the Next.js app listens on inside the container."
  type        = number
  default     = 3000
}

variable "app_cpu" {
  description = "Fargate task CPU units (256 = .25 vCPU)."
  type        = number
  default     = 512
}

variable "app_memory" {
  description = "Fargate task memory in MB."
  type        = number
  default     = 1024
}

variable "app_desired_count" {
  description = "Number of running ECS tasks."
  type        = number
  default     = 2
}

variable "domain_name" {
  description = "Domain name to serve the app on (e.g. carecoord.yourorg.com). Leave empty to skip Route53/ACM and use the raw ALB DNS name over HTTP only until you're ready to attach a domain — see infra/README.md."
  type        = string
  default     = ""
}

variable "route53_zone_id" {
  description = "Existing Route53 hosted zone ID for domain_name. Required only if domain_name is set and you want Terraform to manage the DNS record and ACM validation."
  type        = string
  default     = ""
}

variable "alert_email" {
  description = "Email address to notify on CloudTrail/security-relevant alarms. Leave empty to skip creating the SNS subscription."
  type        = string
  default     = ""
}
