import ExcelJS from "exceljs";
import { requirePermission } from "@/lib/dal";
import { db } from "@/lib/db";
import { writeAuditLog } from "@/lib/audit";
import { getBillingRoster } from "@/lib/data/billing";
import { filterBillingRows, type BillingFilters } from "@/lib/billing";
import { formatDate, titleCase } from "@/lib/format";

// Re-runs the same filters the Billing page's client table used, against a
// fresh server-side read of the roster — the export is never just a dump of
// whatever the client already had in memory, and it's recorded (BillingExport
// + audit log) per the "who/when/which filters/how many" recordkeeping
// requirement for finalized monthly rosters.
export async function POST(request: Request) {
  const session = await requirePermission("EXPORT_BILLING");
  const formData = await request.formData();

  const str = (key: string) => {
    const v = formData.get(key);
    return typeof v === "string" && v.trim() ? v.trim() : "";
  };

  const filters: BillingFilters = {
    status: str("status"),
    insurancePlan: str("insurancePlan"),
    eligibilityVerified: str("eligibilityVerified"),
    coordinatorId: str("coordinatorId"),
    billingInclusion: str("billingInclusion"),
  };
  const billingMonth = str("billingMonth") || new Date().toISOString().slice(0, 7);

  const { rows } = await getBillingRoster();
  const filtered = filterBillingRows(rows, filters);

  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet("Billing Roster");
  sheet.columns = [
    { header: "First Name", key: "firstName", width: 16 },
    { header: "Last Name", key: "lastName", width: 16 },
    { header: "Date of Birth", key: "dateOfBirth", width: 14 },
    { header: "Address", key: "address", width: 30 },
    { header: "Phone", key: "phone", width: 16 },
    { header: "Insurance Plan", key: "insurancePlan", width: 20 },
    { header: "Medicaid ID", key: "medicaidId", width: 16 },
    { header: "Subscriber ID", key: "subscriberId", width: 16 },
    { header: "Activity Status", key: "status", width: 16 },
    { header: "Eligibility Status", key: "eligibilityStatus", width: 16 },
    { header: "Enrollment Date", key: "enrollmentDate", width: 14 },
    { header: "Termination Date", key: "terminationDate", width: 14 },
    { header: "Graduation Date", key: "graduationDate", width: 14 },
    { header: "Assigned Care Coordinator", key: "coordinatorName", width: 24 },
    { header: "Billing Month", key: "billingMonth", width: 14 },
    { header: "Billing Eligibility", key: "billingEligibility", width: 16 },
    { header: "Reason Excluded", key: "reasonExcluded", width: 26 },
  ];
  sheet.getRow(1).font = { bold: true };

  for (const r of filtered) {
    sheet.addRow({
      firstName: r.firstName,
      lastName: r.lastName,
      dateOfBirth: formatDate(r.dateOfBirth),
      address: r.address ?? "",
      phone: r.phone ?? "",
      insurancePlan: r.insurancePlan ?? "",
      medicaidId: r.medicaidId ?? "",
      subscriberId: r.subscriberId ?? "",
      status: titleCase(r.status),
      eligibilityStatus: r.eligibilityVerified === true ? "Verified" : r.eligibilityVerified === false ? "Unverified" : "Not Set",
      enrollmentDate: formatDate(r.enrollmentDate),
      terminationDate: r.terminationDate ? formatDate(r.terminationDate) : "",
      graduationDate: r.graduationDate ? formatDate(r.graduationDate) : "",
      coordinatorName: r.coordinatorName,
      billingMonth,
      billingEligibility: r.billingEligible ? "Included" : "Excluded",
      reasonExcluded: r.billingExclusionReason ?? "",
    });
  }

  const infoSheet = workbook.addWorksheet("Export Info");
  infoSheet.columns = [
    { key: "label", width: 20 },
    { key: "value", width: 60 },
  ];
  infoSheet.addRows([
    { label: "Generated By", value: session.name },
    { label: "Generated At", value: new Date().toLocaleString("en-US") },
    { label: "Billing Month", value: billingMonth },
    { label: "Filters Applied", value: JSON.stringify(filters) },
    { label: "Members Included", value: filtered.length },
  ]);

  await db.billingExport.create({
    data: {
      clinicId: session.clinicId,
      generatedById: session.userId,
      billingMonth,
      filters,
      memberCount: filtered.length,
    },
  });

  await writeAuditLog({
    userId: session.userId,
    action: "EXPORT",
    resource: "BillingExport",
    metadata: { billingMonth, filters, memberCount: filtered.length, memberIds: filtered.map((r) => r.id) },
  });

  const buffer = await workbook.xlsx.writeBuffer();

  return new Response(buffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="billing-roster-${billingMonth}.xlsx"`,
    },
  });
}
